language: python
python:
  - "2.7"
before_install:
 - sudo apt-get update
 - sudo apt-get install chromium-chromedriver
before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
# command to install dependencies
install: 
  - "pip install -r requirements.txt"
# command to run tests
script:
  - make clean
  - make test
  - nohup python main.py &
  - cd tests && lettuce
  - pkill -9 python