language: python
dist: trusty
python:
  - "2.7"
addons:
  chrome: stable
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - nohup python main.py &
  #- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost

install: 
  - "pip install -r requirements.txt"
  - wget http://chromedriver.storage.googleapis.com/2.26/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - PATH=${PATH}:$(pwd)
# command to run tests
script:
  - make clean
  - make test
  - cd tests && lettuce

after_script: pkill -9 python