language: python
python:
  - "2.7"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

install: 
  - "pip install -r requirements.txt"
  - wget http://chromedriver.storage.googleapis.com/2.22/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - PATH=${PATH}:$(pwd)
# command to run tests
script:
  - make clean
  - make test
  - nohup python main.py &
  - cd tests && lettuce
  - pkill -9 python